### ISSUE TITLE
Archetype not compatible anymore with the most recent Miredot site.

### ISSUE THREAD

**Issue by DenEwout** [ovelindstrom/archetype-miredot#1]
Hi,

Thanks for taking the time to make a maven archetype for Miredot! We recently changed our licensing scheme, removing the availability of the free version for commercial users.

Open source users can still request a regular offline free key via e-mail or online support. Commercial users can sign up for a one-month trial at my.miredot.com.

Would it be okay to send you a pull request to clarify these things in the readme? (and change the config suit open-source and commercial users).

Kind regards,

Ewout.

**Comment by ovelindstrom** [comment]
Hi,

is this pull request coming ??

/Ove
